### PR TITLE
Support building for node v12

### PR DESCRIPTION
**Pull request by svenmeys**
We needed this for our production workload.

After some googling and hack and slashing through different documentations I came up with this.
May not be pretty but it seems to be holding up.

### CODE REVIEW

**Comment by cainvommars** [comment]
this could fix https://github.com/joyent/node-bunyan-syslog/issues/53 <3

**Comment by cainvommars** [comment]
@svenmeys how are you handling this right now? running your own build?

**Comment by svenmeys** [comment]
@cainvommars Yes, it's running in production. Just replaced the package.json entry with svenmeys/node-bunyan-syslog

**Comment by melloc** [comment]
Merged in 1261cf7, along with some additional cleanup. I'll put together a v0.3.3 release.

**Pull request closed without merging**
